DOMAIN = "myscoreboard"
DEFAULT_SCAN_INTERVAL = 120

LEAGUE_PATHS = {
    # North American Leagues
    "NCAAF": "football/college-football",
    "NBA": "basketball/nba",
    "WNBA": "basketball/wnba",
    "NBAG": "basketball/nba-development",
    "NCAAM": "basketball/mens-college-basketball",
    "NCAAM_MM": "basketball/mens-college-basketball",
    "NCAAW": "basketball/womens-college-basketball",
    "NCAAB": "baseball/college-baseball",
    "PLL": "lacrosse/pll",
    "NLL": "lacrosse/nll",
    "MLB": "baseball/mlb",
    "NFL": "football/nfl",
    "NHL": "hockey/nhl",
    "MLS": "soccer/usa.1",
    "RUGBY": "rugby/scorepanel",
    "WBC": "baseball/world-baseball-classic",
    # International Soccer
    "AFC_ASIAN_CUP": "soccer/afc.cup",
    "AFC_ASIAN_CUP_Q": "soccer/afc.cupq",
    "AFF_CUP": "soccer/aff.championship",
    "AFR_NATIONS_CUP": "soccer/caf.nations",
    "AFR_NATIONS_CUP_Q": "soccer/caf.nations_qual",
    "AFR_NATIONS_CHAMPIONSHIP": "soccer/caf.championship",
    "CONCACAF_GOLD_CUP": "soccer/concacaf.gold",
    "CONCACAF_NATIONS_Q": "soccer/concacaf.nations.league_qual",
    "CONCACAF_WOMENS_CHAMPIONSHIP": "soccer/concacaf.womens.championship",
    "CONMEBOL_COPA_AMERICA": "soccer/conmebol.america",
    "FIFA_CLUB_WORLD_CUP": "soccer/fifa.cwc",
    "FIFA_CONFEDERATIONS_CUP": "soccer/fifa.confederations",
    "FIFA_MENS_FRIENDLIES": "soccer/fifa.friendly",
    "FIFA_MENS_OLYMPICS": "soccer/fifa.olympics",
    "FIFA_WOMENS_FRIENDLIES": "soccer/fifa.friendly.w",
    "FIFA_WOMENS_OLYMPICS": "soccer/fifa.w.olympics",
    "FIFA_WOMENS_WORLD_CUP": "soccer/fifa.wwc",
    "FIFA_WORLD_CUP": "soccer/fifa.world",
    "FIFA_WORLD_CUP_Q_AFC": "soccer/fifa.worldq.afc",
    "FIFA_WORLD_CUP_Q_CAF": "soccer/fifa.worldq.caf",
    "FIFA_WORLD_CUP_Q_CONCACAF": "soccer/fifa.worldq.concacaf",
    "FIFA_WORLD_CUP_Q_CONMEBOL": "soccer/fifa.worldq.conmebol",
    "FIFA_WORLD_CUP_Q_OFC": "soccer/fifa.worldq.ofc",
    "FIFA_WORLD_CUP_Q_UEFA": "soccer/fifa.worldq.uefa",
    "FIFA_WORLD_U17": "soccer/fifa.world.u17",
    "FIFA_WORLD_U20": "soccer/fifa.world.u20",
    "UEFA_CHAMPIONS": "soccer/uefa.champions",
    "UEFA_WOMENS_CHAMPIONS": "soccer/uefa.wchampions",
    "UEFA_EUROPA": "soccer/uefa.europa",
    "UEFA_EUROPA_CONF": "soccer/uefa.europa.conf",
    "UEFA_EUROPEAN_CHAMPIONSHIP": "soccer/uefa.euro",
    "UEFA_EUROPEAN_CHAMPIONSHIP_Q": "soccer/uefa.euroq",
    "UEFA_EUROPEAN_CHAMPIONSHIP_U19": "soccer/uefa.euro.u19",
    "UEFA_EUROPEAN_CHAMPIONSHIP_U21": "soccer/uefa.euro_u21",
    "UEFA_NATIONS": "soccer/uefa.nations",
    "SAFF_CHAMPIONSHIP": "soccer/afc.saff.championship",
    "WOMENS_EUROPEAN_CHAMPIONSHIP": "soccer/uefa.weuro",
    "UEFA_WOMENS_NATIONS": "soccer/uefa.w.nations",
    # UK / Ireland Soccer
    "ENG_CARABAO_CUP": "soccer/eng.league_cup",
    "ENG_CHAMPIONSHIP": "soccer/eng.2",
    "ENG_EFL": "soccer/eng.trophy",
    "ENG_FA_CUP": "soccer/eng.fa",
    "ENG_LEAGUE_1": "soccer/eng.3",
    "ENG_LEAGUE_2": "soccer/eng.4",
    "ENG_NATIONAL": "soccer/eng.5",
    "ENG_PREMIER_LEAGUE": "soccer/eng.1",
    "IRL_PREM": "soccer/irl.1",
    "NIR_PREM": "soccer/nir.1",
    "SCO_CIS": "soccer/sco.cis",
    "SCO_CHALLENGE_CUP": "soccer/sco.challenge",
    "SCO_CHAMPIONSHIP": "soccer/sco.2",
    "SCO_CUP": "soccer/sco.tennents",
    "SCO_LEAGUE_1": "soccer/sco.3",
    "SCO_LEAGUE_2": "soccer/sco.4",
    "SCO_PREM": "soccer/sco.1",
    "WAL_PREM": "soccer/wal.1",
    "ENG_WSL": "soccer/eng.w.1",
    # European Soccer
    "AUT_BUNDESLIGA": "soccer/aut.1",
    "BEL_DIV_A": "soccer/bel.1",
    "DEN_SAS_LIGAEN": "soccer/den.1",
    "ESP_COPA_DEL_REY": "soccer/esp.copa_del_rey",
    "ESP_LALIGA": "soccer/esp.1",
    "ESP_SEGUNDA_DIV": "soccer/esp.2",
    "FRA_COUPE_DE_FRANCE": "soccer/fra.coupe_de_france",
    "FRA_COUPE_DE_LA_LIGUE": "soccer/fra.coupe_de_la_ligue",
    "FRA_LIGUE_1": "soccer/fra.1",
    "FRA_LIGUE_2": "soccer/fra.2",
    "GER_2_BUNDESLIGA": "soccer/ger.2",
    "GER_BUNDESLIGA": "soccer/ger.1",
    "GER_DFB_POKAL": "soccer/ger.dfb_pokal",
    "GRE_SUPER_LEAGUE": "soccer/gre.1",
    "ISR_PREMIER_LEAGUE": "soccer/isr.1",
    "ITA_SERIE_A": "soccer/ita.1",
    "ITA_SERIE_B": "soccer/ita.2",
    "ITA_COPPA_ITALIA": "soccer/ita.coppa_italia",
    "MLT_PREMIER_LEAGUE": "soccer/mlt.1",
    "NED_EERSTE_DIVISIE": "soccer/ned.2",
    "NED_EREDIVISIE": "soccer/ned.1",
    "NED_KNVB_BEKER": "soccer/ned.cup",
    "NOR_ELITESERIEN": "soccer/nor.1",
    "POR_LIGA": "soccer/por.1",
    "ROU_FIRST_DIV": "soccer/rou.1",
    "RUS_PREMIER_LEAGUE": "soccer/rus.1",
    "SUI_SUPER_LEAGUE": "soccer/sui.1",
    "SWE_ALLSVENSKANLIGA": "soccer/swe.1",
    "TUR_SUPER_LIG": "soccer/tur.1",
    # South American Soccer
    "ARG_COPA": "soccer/arg.copa",
    "ARG_NACIONAL_B": "soccer/arg.2",
    "ARG_PRIMERA_DIV_B": "soccer/arg.3",
    "ARG_PRIMERA_DIV_C": "soccer/arg.4",
    "ARG_PRIMERA_DIV_D": "soccer/arg.5",
    "ARG_SUPERLIGA": "soccer/arg.1",
    "BOL_LIGA_PRO": "soccer/bol.1",
    "BRA_CAMP_CARIOCA": "soccer/bra.camp.carioca",
    "BRA_CAMP_GAUCHO": "soccer/bra.camp.gaucho",
    "BRA_CAMP_MINEIRO": "soccer/bra.camp.mineiro",
    "BRA_CAMP_PAULISTA": "soccer/bra.camp.paulista",
    "BRA_COPA": "soccer/bra.copa_do_brazil",
    "BRA_SERIE_A": "soccer/bra.1",
    "BRA_SERIE_B": "soccer/bra.2",
    "BRA_SERIE_C": "soccer/bra.3",
    "CHI_COPA": "soccer/chi.copa_chi",
    "CHI_PRIMERA_DIV": "soccer/chi.1",
    "COL_COPA": "soccer/col.copa",
    "COL_PRIMERA_A": "soccer/col.1",
    "COL_PRIMERA_B": "soccer/col.2",
    "CONMEBOL_COPA_LIBERTADORES": "soccer/conmebol.libertadores",
    "CONMEBOL_COPA_SUDAMERICANA": "soccer/conmebol.sudamericana",
    "ECU_PRIMERA_A": "soccer/ecu.1",
    "PAR_PRIMERA_DIV": "soccer/par.1",
    "PER_PRIMERA_PRO": "soccer/per.1",
    "URU_PRIMERA_DIV": "soccer/uru.1",
    "VEN_PRIMERA_PRO": "soccer/ven.1",
    # North American Soccer
    "CONCACAF_CHAMPIONS": "soccer/concacaf.champions",
    "CONCACAF_LEAGUE": "soccer/concacaf.league",
    "CRC_PRIMERA_DIV": "soccer/crc.1",
    "GUA_LIGA_NACIONAL": "soccer/gua.1",
    "HON_PRIMERA_DIV": "soccer/hon.1",
    "JAM_PREMIER_LEAGUE": "soccer/jam.1",
    "MEX_ASCENSO_MX": "soccer/mex.2",
    "MEX_COPA_MX": "soccer/mex.copa_mx",
    "MEX_LIGA_BANCOMER": "soccer/mex.1",
    "SLV_PRIMERA_DIV": "soccer/slv.1",
    "USA_MLS": "soccer/usa.1",
    "USA_NCAA_SL_M": "soccer/usa.ncaa.m.1",
    "USA_NCAA_SL_W": "soccer/usa.ncaa.w.1",
    "USA_NASL": "soccer/usa.nasl",
    "NWSL": "soccer/usa.nwsl",
    "USA_OPEN": "soccer/usa.open",
    "USA_USL": "soccer/usa.usl.1",
    "NSL": "soccer/can.w.nsl",
    # Asian Soccer
    "AFC_CHAMPIONS": "soccer/afc.champions",
    "AUS_A_LEAGUE": "soccer/aus.1",
    "AUS_A_WOMEN": "soccer/aus.w.1",
    "CHN_SUPER_LEAGUE": "soccer/chn.1",
    "IDN_SUPER_LEAGUE": "soccer/idn.1",
    "IND_I_LEAGUE": "soccer/ind.2",
    "IND_SUPER_LEAGUE": "soccer/ind.1",
    "JPN_J_LEAGUE": "soccer/jpn.1",
    "MYS_SUPER_LEAGUE": "soccer/mys.1",
    "SGP_PREMIER_LEAGUE": "soccer/sgp.1",
    "THA_PREMIER_LEAGUE": "soccer/tha.1",
    # African Soccer
    "CAF_CHAMPIONS": "soccer/caf.champions",
    "CAF_CONFED_CUP": "soccer/caf.confed",
    "GHA_PREMIERE_LEAGUE": "soccer/gha.1",
    "KEN_PREMIERE_LEAGUE": "soccer/ken.1",
    "NGA_PRO_LEAGUE": "soccer/nga.1",
    "RSA_FIRST_DIV": "soccer/rsa.2",
    "RSA_NEDBANK_CUP": "soccer/rsa.nedbank",
    "RSA_PREMIERSHIP": "soccer/rsa.1",
    "RSA_TELKOM_KNOCKOUT": "soccer/rsa.telkom_knockout",
    "UGA_SUPER_LEAGUE": "soccer/uga.1",
    "ZAM_SUPER_LEAGUE": "soccer/zam.1",
    "ZIM_PREMIER_LEAGUE": "soccer/zim.1",
    # Australian Football & Rugby
    "AFL": "australian-football/afl",
    "PREMIERSHIP_RUGBY": "rugby/267979",
    "RUGBY_WORLD_CUP": "rugby/164205",
    "SIX_NATIONS": "rugby/180659",
    "THE_RUGBY_CHAMPIONSHIP": "rugby/244293",
    "EUROPEAN_RUGBY_CHAMPIONS_CUP": "rugby/271937",
    "UNITED_RUGBY_CHAMPIONSHIP": "rugby/270557",
    "SUPER_RUGBY_PACIFIC": "rugby/242041",
    "OLYMPIC_MENS_7S": "rugby/282",
    "OLYMPIC_WOMENS_RUGBY_SEVENS": "rugby/283",
    "INTERNATIONAL_TEST_MATCH": "rugby/289234",
    "URBA_TOP_12": "rugby/289279",
    "MITRE_10_CUP": "rugby/270563",
    "MAJOR_LEAGUE_RUGBY": "rugby/289262",
}

# Human-friendly names for the UI league picker
LEAGUE_NAMES = {
    # North American
    "NHL": "NHL (Hockey)",
    "NBA": "NBA (Basketball)",
    "WNBA": "WNBA (Women's Basketball)",
    "NBAG": "NBA G League",
    "NFL": "NFL (Football)",
    "MLB": "MLB (Baseball)",
    "MLS": "MLS (Soccer)",
    "NCAAF": "NCAA Football (FBS)",
    "NCAAM": "NCAA Men's Basketball",
    "NCAAM_MM": "NCAA March Madness",
    "NCAAW": "NCAA Women's Basketball",
    "NCAAB": "NCAA Baseball",
    "PLL": "PLL (Lacrosse)",
    "NLL": "NLL (Lacrosse)",
    "WBC": "World Baseball Classic",
    "NWSL": "NWSL (Women's Soccer)",
    # UK / Ireland Soccer
    "ENG_PREMIER_LEAGUE": "English Premier League",
    "ENG_CHAMPIONSHIP": "English Championship",
    "ENG_LEAGUE_1": "English League One",
    "ENG_LEAGUE_2": "English League Two",
    "ENG_NATIONAL": "English National League",
    "ENG_FA_CUP": "FA Cup",
    "ENG_CARABAO_CUP": "Carabao Cup",
    "ENG_EFL": "EFL Trophy",
    "ENG_WSL": "Women's Super League",
    "SCO_PREM": "Scottish Premiership",
    "SCO_CHAMPIONSHIP": "Scottish Championship",
    "SCO_CUP": "Scottish Cup",
    "IRL_PREM": "League of Ireland Premier",
    "WAL_PREM": "Welsh Premier League",
    # European Soccer
    "UEFA_CHAMPIONS": "UEFA Champions League",
    "UEFA_EUROPA": "UEFA Europa League",
    "UEFA_EUROPA_CONF": "UEFA Conference League",
    "UEFA_NATIONS": "UEFA Nations League",
    "UEFA_EUROPEAN_CHAMPIONSHIP": "UEFA Euro Championship",
    "UEFA_EUROPEAN_CHAMPIONSHIP_Q": "UEFA Euro Qualifiers",
    "ESP_LALIGA": "La Liga (Spain)",
    "ESP_SEGUNDA_DIV": "La Liga 2 (Spain)",
    "ESP_COPA_DEL_REY": "Copa del Rey",
    "GER_BUNDESLIGA": "Bundesliga (Germany)",
    "GER_2_BUNDESLIGA": "2. Bundesliga (Germany)",
    "GER_DFB_POKAL": "DFB-Pokal",
    "ITA_SERIE_A": "Serie A (Italy)",
    "ITA_SERIE_B": "Serie B (Italy)",
    "ITA_COPPA_ITALIA": "Coppa Italia",
    "FRA_LIGUE_1": "Ligue 1 (France)",
    "FRA_LIGUE_2": "Ligue 2 (France)",
    "NED_EREDIVISIE": "Eredivisie (Netherlands)",
    "POR_LIGA": "Primeira Liga (Portugal)",
    "BEL_DIV_A": "Belgian First Division A",
    "TUR_SUPER_LIG": "Turkish Super Lig",
    "GRE_SUPER_LEAGUE": "Greek Super League",
    "AUT_BUNDESLIGA": "Austrian Bundesliga",
    "SUI_SUPER_LEAGUE": "Swiss Super League",
    "DEN_SAS_LIGAEN": "Danish Superliga",
    "NOR_ELITESERIEN": "Norwegian Eliteserien",
    "SWE_ALLSVENSKANLIGA": "Swedish Allsvenskan",
    "RUS_PREMIER_LEAGUE": "Russian Premier League",
    "ROU_FIRST_DIV": "Romanian Liga I",
    # International Soccer
    "FIFA_WORLD_CUP": "FIFA World Cup",
    "FIFA_WORLD_CUP_Q_UEFA": "World Cup Qualifiers (UEFA)",
    "FIFA_WORLD_CUP_Q_CONCACAF": "World Cup Qualifiers (CONCACAF)",
    "FIFA_WORLD_CUP_Q_CONMEBOL": "World Cup Qualifiers (CONMEBOL)",
    "FIFA_WORLD_CUP_Q_AFC": "World Cup Qualifiers (AFC)",
    "FIFA_WORLD_CUP_Q_CAF": "World Cup Qualifiers (CAF)",
    "FIFA_WORLD_CUP_Q_OFC": "World Cup Qualifiers (OFC)",
    "FIFA_WOMENS_WORLD_CUP": "FIFA Women's World Cup",
    "FIFA_CLUB_WORLD_CUP": "FIFA Club World Cup",
    "FIFA_MENS_FRIENDLIES": "International Friendlies (Men)",
    "FIFA_WOMENS_FRIENDLIES": "International Friendlies (Women)",
    "FIFA_MENS_OLYMPICS": "Olympics Men's Football",
    "FIFA_WOMENS_OLYMPICS": "Olympics Women's Football",
    "CONMEBOL_COPA_AMERICA": "Copa America",
    "CONMEBOL_COPA_LIBERTADORES": "Copa Libertadores",
    "CONMEBOL_COPA_SUDAMERICANA": "Copa Sudamericana",
    "CONCACAF_GOLD_CUP": "CONCACAF Gold Cup",
    "CONCACAF_CHAMPIONS": "CONCACAF Champions Cup",
    "AFC_ASIAN_CUP": "AFC Asian Cup",
    "AFC_CHAMPIONS": "AFC Champions League",
    "AFR_NATIONS_CUP": "Africa Cup of Nations",
    # South American Soccer
    "ARG_SUPERLIGA": "Argentine Primera Division",
    "BRA_SERIE_A": "Brasileirao Serie A",
    "BRA_SERIE_B": "Brasileirao Serie B",
    "COL_PRIMERA_A": "Colombian Primera A",
    "MEX_LIGA_BANCOMER": "Liga MX (Mexico)",
    # Asian / Oceanian Soccer
    "AUS_A_LEAGUE": "A-League (Australia)",
    "JPN_J_LEAGUE": "J1 League (Japan)",
    "CHN_SUPER_LEAGUE": "Chinese Super League",
    "IND_SUPER_LEAGUE": "Indian Super League",
    # African Soccer
    "RSA_PREMIERSHIP": "South African Premiership",
    # Rugby
    "RUGBY": "Rugby (All)",
    "SIX_NATIONS": "Six Nations",
    "RUGBY_WORLD_CUP": "Rugby World Cup",
    "THE_RUGBY_CHAMPIONSHIP": "The Rugby Championship",
    "SUPER_RUGBY_PACIFIC": "Super Rugby Pacific",
    "PREMIERSHIP_RUGBY": "Premiership Rugby",
    "UNITED_RUGBY_CHAMPIONSHIP": "United Rugby Championship",
    "EUROPEAN_RUGBY_CHAMPIONS_CUP": "European Rugby Champions Cup",
    "MAJOR_LEAGUE_RUGBY": "Major League Rugby",
    # Australian Football
    "AFL": "AFL (Australian Football)",
}

# ESPN game status type IDs mapped to game states
# gameState: 0 = pre-game, 1 = in-progress, 2 = completed
GAME_STATE_PRE = 0
GAME_STATE_LIVE = 1
GAME_STATE_FINAL = 2
